namespace ESB.Extensions.Library.Resolvers.Bre
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.4200
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary", IsNullable = false)]
    public partial class BRE
    {

        private string policyField;

        private bool recognizeMessageFormatField;

        private bool recognizeMessageFormatFieldSpecified;

        private bool useMsgField;

        private bool useMsgFieldSpecified;

        private string versionField;

        private bool useMsgCtxtField;

        private bool useMsgCtxtFieldSpecified;

        private string msgCtxtValuesField;

        private bool usePolicyBrokerField;

        private bool usePolicyBrokerFieldSpecified;

        private bool useDebugInterceptorField;

        private bool useDebugInterceptorFieldSpecified;

        private string debugOutputPathField;

        private bool useRepromotionField;

        private bool useRepromotionFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string policy
        {
            get
            {
                return this.policyField;
            }
            set
            {
                this.policyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool recognizeMessageFormat
        {
            get
            {
                return this.recognizeMessageFormatField;
            }
            set
            {
                this.recognizeMessageFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recognizeMessageFormatSpecified
        {
            get
            {
                return this.recognizeMessageFormatFieldSpecified;
            }
            set
            {
                this.recognizeMessageFormatFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useMsg
        {
            get
            {
                return this.useMsgField;
            }
            set
            {
                this.useMsgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useMsgSpecified
        {
            get
            {
                return this.useMsgFieldSpecified;
            }
            set
            {
                this.useMsgFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useMsgCtxt
        {
            get
            {
                return this.useMsgCtxtField;
            }
            set
            {
                this.useMsgCtxtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useMsgCtxtSpecified
        {
            get
            {
                return this.useMsgCtxtFieldSpecified;
            }
            set
            {
                this.useMsgCtxtFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string msgCtxtValues
        {
            get
            {
                return this.msgCtxtValuesField;
            }
            set
            {
                this.msgCtxtValuesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool usePolicyBroker
        {
            get
            {
                return this.usePolicyBrokerField;
            }
            set
            {
                this.usePolicyBrokerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usePolicyBrokerSpecified
        {
            get
            {
                return this.usePolicyBrokerFieldSpecified;
            }
            set
            {
                this.usePolicyBrokerFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useDebugInterceptor
        {
            get
            {
                return this.useDebugInterceptorField;
            }
            set
            {
                this.useDebugInterceptorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useDebugInterceptorSpecified
        {
            get
            {
                return this.useDebugInterceptorFieldSpecified;
            }
            set
            {
                this.useDebugInterceptorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string debugOutputPath
        {
            get
            {
                return this.debugOutputPathField;
            }
            set
            {
                this.debugOutputPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useRepromotion
        {
            get
            {
                return this.useRepromotionField;
            }
            set
            {
                this.useRepromotionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useRepromotionSpecified
        {
            get
            {
                return this.useRepromotionFieldSpecified;
            }
            set
            {
                this.useRepromotionFieldSpecified = value;
            }
        }
    }
}